"""unique_fields

Revision ID: 4b5f663e968e
Revises: 5f22c30d4d26
Create Date: 2025-04-27 21:43:46.336358

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b5f663e968e"
down_revision: Union[str, None] = "5f22c30d4d26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("audiences", sa.Column("unique_field", sa.String(), nullable=False))
    op.create_index(
        op.f("ix_audiences_unique_field"), "audiences", ["unique_field"], unique=True
    )
    op.add_column("courses", sa.Column("unique_field", sa.String(), nullable=False))
    op.create_index(
        op.f("ix_courses_unique_field"), "courses", ["unique_field"], unique=True
    )
    op.drop_column("courses", "lks_id")
    op.create_index(
        op.f("ix_departments_lks_id"), "departments", ["lks_id"], unique=True
    )
    op.add_column("disciplines", sa.Column("unique_field", sa.String(), nullable=False))
    op.create_index(
        op.f("ix_disciplines_unique_field"),
        "disciplines",
        ["unique_field"],
        unique=True,
    )
    op.create_index(op.f("ix_faculties_lks_id"), "faculties", ["lks_id"], unique=True)
    op.create_index(op.f("ix_filials_lks_id"), "filials", ["lks_id"], unique=True)
    op.create_index(op.f("ix_groups_lks_id"), "groups", ["lks_id"], unique=True)
    op.add_column(
        "schedule_pairs", sa.Column("unique_field", sa.String(), nullable=False)
    )
    op.create_index(
        op.f("ix_schedule_pairs_unique_field"),
        "schedule_pairs",
        ["unique_field"],
        unique=True,
    )
    op.create_index(op.f("ix_teachers_lks_id"), "teachers", ["lks_id"], unique=True)
    op.create_index(
        op.f("ix_universities_lks_id"), "universities", ["lks_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_universities_lks_id"), table_name="universities")
    op.drop_index(op.f("ix_teachers_lks_id"), table_name="teachers")
    op.drop_index(op.f("ix_schedule_pairs_unique_field"), table_name="schedule_pairs")
    op.drop_column("schedule_pairs", "unique_field")
    op.drop_index(op.f("ix_groups_lks_id"), table_name="groups")
    op.drop_index(op.f("ix_filials_lks_id"), table_name="filials")
    op.drop_index(op.f("ix_faculties_lks_id"), table_name="faculties")
    op.drop_index(op.f("ix_disciplines_unique_field"), table_name="disciplines")
    op.drop_column("disciplines", "unique_field")
    op.drop_index(op.f("ix_departments_lks_id"), table_name="departments")
    op.add_column(
        "courses", sa.Column("lks_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f("ix_courses_unique_field"), table_name="courses")
    op.drop_column("courses", "unique_field")
    op.drop_index(op.f("ix_audiences_unique_field"), table_name="audiences")
    op.drop_column("audiences", "unique_field")
    # ### end Alembic commands ###
