"""rm_discipline_lks_id

Revision ID: 5f22c30d4d26
Revises: 6fcf06da51ff
Create Date: 2025-04-22 21:23:13.110017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f22c30d4d26'
down_revision: Union[str, None] = '6fcf06da51ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disciplines', 'lks_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciplines', sa.Column('lks_id', sa.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
