"""new

Revision ID: 6fcf06da51ff
Revises: a89d1ccb712b
Create Date: 2025-04-20 17:21:05.830660

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6fcf06da51ff"
down_revision: Union[str, None] = "a89d1ccb712b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("disciplines", "lks_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("disciplines", "lks_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
