"""initial

Revision ID: a89d1ccb712b
Revises: 
Create Date: 2025-04-20 10:41:49.170414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a89d1ccb712b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synchronizations',
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audiences',
    sa.Column('lks_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=True),
    sa.Column('map_url', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sync_id'], ['synchronizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disciplines',
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('act_type', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lks_id', sa.Uuid(), nullable=False),
    sa.Column('abbr', sa.String(), nullable=False),
    sa.Column('sync_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sync_id'], ['synchronizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lks_id', sa.Uuid(), nullable=False),
    sa.Column('sync_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sync_id'], ['synchronizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('universities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lks_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbr', sa.String(), nullable=False),
    sa.Column('sync_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sync_id'], ['synchronizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filials',
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lks_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbr', sa.String(), nullable=False),
    sa.Column('sync_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sync_id'], ['synchronizations.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_pairs',
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('week', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.ForeignKeyConstraint(['sync_id'], ['synchronizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faculties',
    sa.Column('filial_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lks_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbr', sa.String(), nullable=False),
    sa.Column('sync_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filial_id'], ['filials.id'], ),
    sa.ForeignKeyConstraint(['sync_id'], ['synchronizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_pair_audience',
    sa.Column('schedule_pair_id', sa.Integer(), nullable=False),
    sa.Column('audience_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audience_id'], ['audiences.id'], ),
    sa.ForeignKeyConstraint(['schedule_pair_id'], ['schedule_pairs.id'], ),
    sa.PrimaryKeyConstraint('schedule_pair_id', 'audience_id')
    )
    op.create_table('schedule_pair_teacher',
    sa.Column('schedule_pair_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_pair_id'], ['schedule_pairs.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('schedule_pair_id', 'teacher_id')
    )
    op.create_table('departments',
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lks_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbr', sa.String(), nullable=False),
    sa.Column('sync_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.ForeignKeyConstraint(['sync_id'], ['synchronizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('course_num', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lks_id', sa.Uuid(), nullable=False),
    sa.Column('abbr', sa.String(), nullable=False),
    sa.Column('sync_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['sync_id'], ['synchronizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('semester_num', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lks_id', sa.Uuid(), nullable=False),
    sa.Column('abbr', sa.String(), nullable=False),
    sa.Column('sync_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['sync_id'], ['synchronizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_pair_group',
    sa.Column('schedule_pair_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['schedule_pair_id'], ['schedule_pairs.id'], ),
    sa.PrimaryKeyConstraint('schedule_pair_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_pair_group')
    op.drop_table('groups')
    op.drop_table('courses')
    op.drop_table('departments')
    op.drop_table('schedule_pair_teacher')
    op.drop_table('schedule_pair_audience')
    op.drop_table('faculties')
    op.drop_table('schedule_pairs')
    op.drop_table('filials')
    op.drop_table('universities')
    op.drop_table('teachers')
    op.drop_table('disciplines')
    op.drop_table('audiences')
    op.drop_table('synchronizations')
    # ### end Alembic commands ###
