services:
  bmstu-schedule-postgres-dc:
    image: postgres:16
    container_name: bmstu-schedule-postgres-dc
    expose:
      - 5432
    ports:
      - "${DB__PORT}:5432"
    environment:
      - POSTGRES_DB=${DB__NAME}
      - POSTGRES_USER=${DB__USER}
      - POSTGRES_PASSWORD=${DB__PASS}
    networks:
      - bmstu_schedule_net

networks:
  bmstu_schedule_net:
    driver: bridge
