services:
  bmstu-schedule-postgres-dc:
    image: postgres:16
    container_name: bmstu-schedule-postgres-dc
    expose:
      - 5432
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - bmstu_schedule_net

networks:
  bmstu_schedule_net:
    driver: bridge
